fixed css issue in custom forms
pefernan/kogito-apps pull request #3
Opened 2021-10-06 11:40 UTC by AjayJagan

css fix for custom forms

2021-10-06 18:12 UTC, pefernan requested changes
This works perfect!

But I'd do two changes:

- Try adding the overflow-y into the html pages that we use for the displayer instead of the component.. I'd prefer that than modifying the body style directly in the component. If that doesn't work I'll be ok with this change as it is
- Update the snapshot for the Displayer :P

2021-10-06 18:12 UTC, pefernan commented on ui-packages/packages/form-displayer/src/envelope/components/FormDisplayer/FormDisplayer.tsx
> +      document.body.style.overflowY = 'auto';
I'm ok with the change but would it be possible to chek if this change works when added directly in the pages we display in the iframe??

https://github.com/pefernan/kogito-apps/blob/KOGITO-5872-custom-forms_runtime_integration/ui-packages/packages/runtime-tools-dev-ui-webapp/resources/form-displayer.html#L20
https://github.com/pefernan/kogito-apps/blob/KOGITO-5872-custom-forms_runtime_integration/ui-packages/packages/task-console-webapp/resources/form-displayer.html#L20

2021-10-07 05:05 UTC, AjayJagan commented on ui-packages/packages/task-form/src/envelope/tests/mocks/Mocks.ts
> +    lastModified: new Date('2021-10-07T04:58:18.311Z')
@pefernan  In the `TaskFormEnvelopeView.test.tsx`, the snapshot was updating because the time was not provided in hte mock, So I added the date with time(ISO string) so that the snapshots won't fail when the time is updated. Let me know if it is ok.

2021-10-13 19:11 UTC, pefernan commented
Already merged!

2021-10-13 19:11 UTC, closed without merging